server:
  port: 9093
eureka:
 client:
  service-url:
   defaultzone: http://locahost:8761/eureka/
   
spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: Arpitha@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
